

sankeyDraw(
  {"nodes": [ 
       {"name":'Overview'},
       {"name":'Pre-Test'},
       {"name":'Introduction'},
       {"name":'Encryption'}, 
       {"name":'Recursion'},
       {"name":'Iterative algorithms'},
       {"name":'While loops'},
       {"name":'For loops'},
       {"name":'Data Structures'},
       {"name": 'Making Decisions'},
       {"name":'Lists'},
       {"name":'Nested loops'},
       {"name":'Time-efficiency'},
       {"name": 'Data Representation'},
       {"name":'Post-Test'},
       {"name":'Iterations + Decisions'},
       ],

    "links": [
      {"source":0,"target":1,"value":235},
      {"source":1,"target":2,"value":223},
      {"source":2,"target":11,"value":4},
      {"source":11,"target":5,"value":2},
      {"source":5,"target":6,"value":145},
      {"source":6,"target":7,"value":140},
      {"source":0,"target":2,"value":22},
      {"source":2,"target":5,"value":138},
      {"source":1,"target":0,"value":5},
      {"source":5,"target":12,"value":1},
      {"source":2,"target":6,"value":5},
      {"source":7,"target":9,"value":68},
      {"source":9,"target":12,"value":10},
      {"source":2,"target":12,"value":16},
      {"source":12,"target":9,"value":41},
      {"source":7,"target":10,"value":57},
      {"source":10,"target":11,"value":96},
      {"source":11,"target":12,"value":86},
      {"source":9,"target":14,"value":2},
      {"source":14,"target":15,"value":2},
      {"source":9,"target":10,"value":55},
      {"source":2,"target":7,"value":7},
      {"source":9,"target":5,"value":4},
      {"source":6,"target":12,"value":2},
      {"source":9,"target":15,"value":15},
      {"source":12,"target":15,"value":33},
      {"source":0,"target":10,"value":1},
      {"source":10,"target":12,"value":8},
      {"source":1,"target":4,"value":3},
      {"source":4,"target":8,"value":2},
      {"source":8,"target":13,"value":1},
      {"source":13,"target":2,"value":1},
      {"source":7,"target":11,"value":4},
      {"source":2,"target":9,"value":11},
      {"source":1,"target":5,"value":10},
      {"source":5,"target":2,"value":2},
      {"source":6,"target":10,"value":3},
      {"source":2,"target":10,"value":3},
      {"source":9,"target":7,"value":1},
      {"source":7,"target":6,"value":4},
      {"source":10,"target":9,"value":6},
      {"source":9,"target":11,"value":5},
      {"source":7,"target":14,"value":1},
      {"source":11,"target":9,"value":3},
      {"source":15,"target":12,"value":1},
      {"source":9,"target":4,"value":1},
      {"source":4,"target":10,"value":1},
      {"source":4,"target":2,"value":2},
      {"source":5,"target":7,"value":3},
      {"source":2,"target":1,"value":12},
      {"source":1,"target":10,"value":1},
      {"source":1,"target":9,"value":2},
      {"source":1,"target":3,"value":1},
      {"source":7,"target":12,"value":4},
      {"source":11,"target":10,"value":2},
      {"source":12,"target":0,"value":1},
      {"source":0,"target":9,"value":1},
      {"source":10,"target":7,"value":1},
      {"source":12,"target":1,"value":1},
      {"source":2,"target":15,"value":1},
      {"source":15,"target":9,"value":1},
      {"source":12,"target":11,"value":1},
      {"source":11,"target":15,"value":2},
      {"source":6,"target":9,"value":2},
      {"source":9,"target":2,"value":1},
      {"source":12,"target":10,"value":2},
      {"source":5,"target":9,"value":1},
      {"source":6,"target":5,"value":2},
      {"source":0,"target":5,"value":1},
      {"source":7,"target":2,"value":1},
      {"source":15,"target":14,"value":1},
      {"source":14,"target":4,"value":1},
      {"source":2,"target":14,"value":1},
      {"source":14,"target":12,"value":1},
      {"source":5,"target":10,"value":1},
      {"source":10,"target":6,"value":1},
      {"source":10,"target":4,"value":1}
    ],
    'sinksRight': false
  }
);
